plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
}

android {
    namespace = "panel.xyper.keygen"
    compileSdk = 36

    defaultConfig {
        applicationId = "panel.xyper.keygen"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // ── Signing Config ────────────────────────────────────────────
    signingConfigs {
        create("release") {
            val ksApp = file("release-key.jks")
            val ksRoot = file("../release-key.jks")

            storeFile = if (ksApp.exists()) ksApp else ksRoot
            storePassword = "290608"
            keyAlias = "Xyper-Panel-Key"
            keyPassword = "290608"
        }
    }

    buildTypes {
        getByName("release") {
            signingConfig = signingConfigs.getByName("release")

            // ── ProGuard / R8 ─────────────────────────────────────
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        getByName("debug") {
            isMinifyEnabled = false
        }
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)

    // ── AndroidX ──────────────────────────────────────────────────
    implementation("androidx.appcompat:appcompat:1.7.1")
    implementation("com.google.android.material:material:1.14.0-alpha10")
    implementation("androidx.constraintlayout:constraintlayout:2.2.1")

    // ── Retrofit + Converters ─────────────────────────────────────
    implementation("com.squareup.retrofit2:retrofit:3.0.0")
    implementation("com.squareup.retrofit2:converter-scalars:3.0.0")
    implementation("com.squareup.retrofit2:converter-gson:3.0.0")

    // ── OkHttp 5.x ────────────────────────────────────────────────
    implementation("com.squareup.okhttp3:okhttp:5.3.2")
    implementation("com.squareup.okhttp3:logging-interceptor:5.3.2")

    // ── Gson ──────────────────────────────────────────────────────
    implementation("com.google.code.gson:gson:2.13.2")

    // ── Lottie ────────────────────────────────────────────────────
    implementation("com.airbnb.android:lottie:6.7.1")

    // ── Coroutines ────────────────────────────────────────────────
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2")

    // ── WorkManager + Core ────────────────────────────────────────
    implementation("androidx.work:work-runtime:2.11.2")
    implementation("androidx.core:core:1.18.0")
}
